tipr_application_homepage:
    pattern:  /
    defaults: { _controller: TiprApplicationBundle:Default:index }

#general

tipr_application_loginDonator:
    pattern: /m/login
    defaults: { _controller: TiprApplicationBundle:Authentication:loginDonator }
    methods: [GET]

tipr_application_loginDonatorProcess:
    pattern: /m/login
    defaults: { _controller: TiprApplicationBundle:Authentication:loginDonatorProcess }
    methods: [POST]

tipr_application_loginRecipient:
    pattern: /login
    defaults: { _controller: TiprApplicationBundle:Authentication:loginRecipient }
    methods: [GET]

tipr_application_loginRecipientProcess:
    pattern: /login
    defaults: { _controller: TiprApplicationBundle:Authentication:loginRecipientProcess }
    methods: [POST]

tipr_application_logoutRecipientProcess:
    pattern: /logout
    defaults: { _controller: TiprApplicationBundle:Authentication:logoutRecipientProcess }
    methods: [GET]

tipr_application_logoutDonatorProcess:
    pattern: /m/logout
    defaults: { _controller: TiprApplicationBundle:Authentication:logoutDonatorProcess }
    methods: [GET]

tipr_application_registerDonator:
    pattern: /m/register
    defaults: { _controller: TiprApplicationBundle:Authentication:registerDonator }
    methods: [GET]

tipr_application_registerRecipient:
    pattern: /register
    defaults: { _controller: TiprApplicationBundle:Authentication:registerRecipient }
    methods: [GET]

tipr_application_registerDonatorProcess:
    pattern: /m/register
    defaults: { _controller: TiprApplicationBundle:Authentication:registerDonatorProcess }
    methods: [POST]

tipr_application_registerRecipientProcess:
    pattern: /register
    defaults: { _controller: TiprApplicationBundle:Authentication:registerRecipientProcess }
    methods: [POST]

#donator

tipr_application_m_donator_overview:
    pattern:  /m/overview
    defaults: { _controller: TiprApplicationBundle:Donator:index }

tipr_application_m_donator_donate:
    pattern:  /m/donate/{username}
    defaults: { _controller: TiprApplicationBundle:Donator:donate }
    methods: [GET]

tipr_application_m_donator_donateProcess:
    pattern:  /m/donate/{username}
    defaults: { _controller: TiprApplicationBundle:Donator:donateProcess }
    methods: [POST]

tipr_application_m_donator_thanks:
    pattern:  /m/thanks/{username}
    defaults: { _controller: TiprApplicationBundle:Donator:thanks }
    methods: [GET]


#recipient

tipr_application_recipient_overview:
    pattern:  /overview
    defaults: { _controller: TiprApplicationBundle:Recipient:index }

tipr_application_recipient_settings:
    pattern:  /settings
    defaults: { _controller: TiprApplicationBundle:Recipient:settings }
    methods: [GET]

tipr_application_recipient_settingsProcess:
    pattern:  /settings
    defaults: { _controller: TiprApplicationBundle:Recipient:settingsProcess }
    methods: [POST]