parameters:
#    tipr_application.example.class: Tipr\ApplicationBundle\Example

services:
#    tipr_application.example:
#        class: %tipr_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
