<?php

namespace Tipr\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgesRepository extends EntityRepository
{
}
