<?php

namespace Tipr\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonatorRepository extends EntityRepository
{
    public function getDonations($donatorID){

    }

}
